### ISSUE TITLE
Explicitly handle SIGPIPE

### ISSUE THREAD

**Issue by ericpruitt** [vandry/mairix#10] opened 2017-12-24 22:53 UTC
When running mairix in a pipeline, mairix does not delete the lock file after receiving SIGPIPE, so running something like `mairix --excerpt-output a:ericpruitt | less` results in `Database .../mairixdb appears to be locked by (pid,node,user)=(6387,sinister,ericpruitt)` the next time around if _less(1)_ was closed before mairix finished writing data the standard output.

**Comment by vandry** [comment] 2017-12-26 21:30
This is a duplicate of https://github.com/rc0/mairix/issues/21

BTW I was thinking of solving the problem not by adding handling for SIGPIPE or other signals, but by removing the need to do locking at all, which would obviate the need to explicit cleanup. For that, see https://github.com/rc0/mairix/issues/25

**Closed as completed by vandry** 2017-12-26 21:30 UTC
